# ========================================
# PharmaVerif - Docker Compose
# Copyright (c) 2026 Anas BENDAIKHA
# ========================================

version: '3.8'

services:
  # ========================================
  # API BACKEND
  # ========================================
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pharmaverif-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - DATABASE_URL=postgresql://pharmaverif:pharmaverif@db:5432/pharmaverif
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_ORIGINS=http://localhost:3000,https://pharmaverif.vercel.app
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/exports:/app/exports
      - ./backend/logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - pharmaverif-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ========================================
  # DATABASE POSTGRESQL
  # ========================================
  db:
    image: postgres:15-alpine
    container_name: pharmaverif-db
    environment:
      - POSTGRES_USER=pharmaverif
      - POSTGRES_PASSWORD=pharmaverif
      - POSTGRES_DB=pharmaverif
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - pharmaverif-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmaverif"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================================
  # REDIS CACHE (optionnel)
  # ========================================
  # redis:
  #   image: redis:7-alpine
  #   container_name: pharmaverif-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped
  #   networks:
  #     - pharmaverif-network
  #   command: redis-server --appendonly yes
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 5

  # ========================================
  # PGADMIN (optionnel - pour dev)
  # ========================================
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pharmaverif-pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@pharmaverif.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   networks:
  #     - pharmaverif-network

# ========================================
# VOLUMES
# ========================================
volumes:
  postgres-data:
    driver: local
  # redis-data:
  #   driver: local

# ========================================
# NETWORKS
# ========================================
networks:
  pharmaverif-network:
    driver: bridge
